name: "S3 Upload multiple files or directories"
description: "Upload files and directories to S3 compatible cloud buckets. Action created by koraykoska and enhanced by ZabasJC"
author: "Eran Sery - ranser102"
runs:
  using: docker
  image: Dockerfile
branding:
  icon: box
  color: red